---
- name: install pip
  apt: name=python-pip state=present

- name: install virtualenv
  pip: name=virtualenv state=present

- name: install specific python requirements in virtualenv
  pip: requirements={{ project_dir}}/requirements.txt
       virtualenv=~/venvs/{{ project_name }}
       virtualenv_python=python{{ python_version }}
  become_user: "{{ project_user }}"
