---
- name: install git
  apt: name=git-core state=present

- name: checkout the source code
  git: repo={{ project_repo }}
       dest={{ project_dir }}
       accept_hostkey=yes
  become_user: "{{ project_user }}"
